name: autotests

on:
  push

jobs:
  test:
  runs-on:   ubuntu-latest

  steps:
    - name: check_repo
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup--python@v4
        with:
          python-version: "3.10"
    - name: Install Chrome
      run: sudo pat-get insatall google-chrome-stable
    - name: Install Dependecies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest